const { withDangerousMod } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');
const withAndroidWidgets = require('react-native-android-widget/app.plugin').default;

/** How often the home-screen widget re-renders while it is visible. */
const TICK_INTERVAL_MS = 60_000;

/**
 * Wraps react-native-android-widget's plugin so each widget re-renders every minute.
 *
 * Android caps `updatePeriodMillis` at one update per 30 minutes, so the generated
 * AppWidgetProvider is replaced with one that also drives a repeating alarm.
 */
function withNonbuWidget(config, params) {
  // Mods registered first run last, so this override lands after the library writes its provider.
  config = withMinuteTick(config, params.widgets);
  return withAndroidWidgets(config, params);
}

function withMinuteTick(config, widgets) {
  return withDangerousMod(config, [
    'android',
    (modConfig) => {
      const appPackage = modConfig.android?.package;
      if (!appPackage) throw new Error('withNonbuWidget: android.package must be set');
      for (const widget of widgets) {
        const widgetPackage = widget.packageName ?? `${appPackage}.widget`;
        const dir = path.join(
          modConfig.modRequest.platformProjectRoot,
          'app/src/main/java',
          ...widgetPackage.split('.'),
        );
        fs.mkdirSync(dir, { recursive: true });
        fs.writeFileSync(path.join(dir, `${widget.name}.java`), tickingProvider(widgetPackage, widget.name));
      }
      return modConfig;
    },
  ]);
}

function tickingProvider(widgetPackage, className) {
  return `package ${widgetPackage};

import android.app.AlarmManager;
import android.app.PendingIntent;
import android.appwidget.AppWidgetManager;
import android.content.ComponentName;
import android.content.Context;
import android.content.Intent;
import android.os.SystemClock;

import com.reactnativeandroidwidget.RNWidgetProvider;

/** Generated by plugins/withNonbuWidget.js; re-renders the widget every minute. */
public class ${className} extends RNWidgetProvider {
    private static final long TICK_INTERVAL_MS = ${TICK_INTERVAL_MS}L;

    @Override
    public void onReceive(Context context, Intent intent) {
        if (tickAction(context).equals(intent.getAction())) {
            AppWidgetManager manager = AppWidgetManager.getInstance(context);
            onUpdate(context, manager, manager.getAppWidgetIds(new ComponentName(context, ${className}.class)));
            return;
        }
        super.onReceive(context, intent);
    }

    @Override
    public void onUpdate(Context context, AppWidgetManager manager, int[] widgetIds) {
        super.onUpdate(context, manager, widgetIds);
        // Alarms are dropped on reboot and app update; Android sends APPWIDGET_UPDATE after both.
        scheduleTick(context);
    }

    @Override
    public void onDisabled(Context context) {
        super.onDisabled(context);
        PendingIntent tick = tickIntent(context, PendingIntent.FLAG_NO_CREATE);
        if (tick != null) {
            context.getSystemService(AlarmManager.class).cancel(tick);
            tick.cancel();
        }
    }

    private static void scheduleTick(Context context) {
        if (tickIntent(context, PendingIntent.FLAG_NO_CREATE) != null) return;
        // Non-wakeup alarm: ticks pause while the screen is off, when nobody can see the widget.
        context.getSystemService(AlarmManager.class).setRepeating(
            AlarmManager.ELAPSED_REALTIME,
            SystemClock.elapsedRealtime() + TICK_INTERVAL_MS,
            TICK_INTERVAL_MS,
            tickIntent(context, 0));
    }

    private static PendingIntent tickIntent(Context context, int flags) {
        Intent intent = new Intent(context, ${className}.class).setAction(tickAction(context));
        return PendingIntent.getBroadcast(context, 0, intent, flags | PendingIntent.FLAG_IMMUTABLE);
    }

    // Must not start with "<package>.WIDGET": RNWidgetProvider treats those as click intents.
    private static String tickAction(Context context) {
        return context.getPackageName() + ".TICK_${className.toUpperCase()}";
    }
}
`;
}

module.exports = withNonbuWidget;
